### ISSUE TITLE
Loading checkpoints fails

### ISSUE THREAD

**Issue by zeeros** [BNN-UPC/RouteNet-Erlang#9]
```
Found a pretrained model, restoring...
BEST CHECKOINT FOUND: 69-9.91.data-00000-of-00001
2022-05-02 11:41:06.107104: W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open ./ckpt_dir/69-9.91.data-00000-of-00001: DATA_LOSS: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    model.load_weights('./ckpt_dir/{}'.format(best))
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2400, in load_weights
    raise ValueError(
ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.
```

**Comment by MiquelFerriol** [comment]
This should be fixed now. 

There was a problem where the code selected the `69-9.91.data-00000-of-00001` file instead of the `69-9.91`.

By simply adding this line: `best = best.replace('.data-00000-of-00001', '')` the problem should be fixed.

Thanks for your time,
Miquel
